package:
  name: orionmdcore
  version: '1.1.3'

source:
  path: ../../

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  string: py_0

requirements:
  pin_depends: strict
  build:
    - ambertools=21.11
    - invoke==1.6.0
    - lxml==4.6.3
    - numpy==1.22.2
    - mdtraj==1.9.7
    - oeommtools==0.1.20
    - openff-toolkit==0.10.2
    - openff-forcefields==2.0.0
    - openmm==7.5.1
    - openmoltools==0.8.8
    - packmol==20.010
    - parmed==3.4.3
    - pdbfixer==1.7
    - pip==22.0.3
    - pyparsing==3.0.7
    - python==3.9
    - pytest==7.0.0
    - setuptools==60.8.1
    - tqdm==4.62.3
  run:
    - ambertools=21.11
    - invoke==1.6.0
    - lxml==4.6.3
    - numpy==1.22.2
    - mdtraj==1.9.7
    - oeommtools==0.1.20
    - openff-toolkit==0.10.2
    - openff-forcefields==2.0.0
    - openmm==7.5.1
    - openmoltools==0.8.8
    - packmol==20.010
    - parmed==3.4.3
    - pdbfixer==1.7
    - pip==22.0.3
    - pyparsing==3.0.7
    - python==3.9
    - pytest==7.0.0
    - setuptools==60.8.1
    - tqdm==4.62.3
test:
  requires:
    - pytest
#  imports:
#    - orionmdcore

about:
  home: https://github.com/oess/orionmdcore
  license: OpenEye proprietary
  summary: Orion MD core package
